### ISSUE TITLE
U8g code conversion to AdafruitSSD1306 library

### ISSUE THREAD

**Issue by ovi4** [basvdijk/arduino-weather#1]
Hi there, i am a beginner trying to adapt your code to my SSD1306 (128x64) SPI oled by using the Adafruitssd1306 library as U8g library doez NOT support the SPI version of SSD1306 display.
I keep getting errors such as SSD1306 class does not have such and such member.
So im thinking that certain argument of a function in U8g library cannot be used for the Adafruit SSD1306 library since they do not exist within that library. A good example is for instance .setFont(). Adafruit only has.setTextSize(). Another thing is on your progect you have 2 pages being displayed alternatively. I cannot see a way of doing the same  when using Adafruit's library. What funct arguments can be used??
Any help is much appreciated TNX.

PS my setup is : arduino uno r3, ssd1306(128x64, spi) display and DHT22 sensor. And yes I have other projects that i've tried testing the hardware with and everything works just fine.

**Comment by basvdijk** [comment]
Hi, this code is quite old so it might not work as expected anymore. It is really hard to tell what the issue could. There is a successor of the U8glib called U8G2 https://github.com/olikraus/u8g2/wiki which might support your screen. I've recently created a video about a weather station with Arduino, unfortunately these are in Dutch: https://arduino-lessen.nl/project/arduino-mini-weerstation However the code might be of use https://github.com/BasOnTech/Arduino-Projects-NL/tree/master/mini-weerstation

**Comment by ovi4** [comment]
Hi, thank you for answering my questions. Well, after "trial and error" with my SSD1306 128x64 (SPI 7 pins) OLED display it turned out that the pinout description (within the U8g library) was incomplete as the RES pin was left out so when  ( SSD1306 128x64) is selected I then connected it to pin RESET on the Arduino UNO board. and strength enough if I select the U8GLIB_SH1106_128X64 u8g(13,11,10,9); it also worked but  had to assign pin 8 as RES pin by simply adding it within brackets so it becomes : U8GLIB_SH1106_128X64 u8g(13,11,10,9,8);  //D0(SCK)=13, DI(MOSI)=11, CS=10, A0(DC)=9, RES(RST)=8. 

***As for my second issue regarding using the Adafruit SSD1306 library to try adapting it to your "weather station" code well, I had to give up on that since I realised that the library itself is really rudimentary and that has not much flexibility to it so, I've now switched to U8g library. I'm yet to try out the U8g2 (like you've  just said, it is the "newer version" of the old U8g library).

***As for the third issue regarding the use of (Adafruit's master DHT sensor) library well, I had to completely remove it from my Arduino library "folder" since the code had trouble compiling it . It was getting confused in choosing the right type of library which is the one you've described within your code 
(arduino-DHT-master).

***On the other hand, thank you for the links, I will still check them out despite the language barrier 👍

Here is one of my weather station code creation "so far" : 
```
/*
This is a Weather Station code with some Bitmap creation by ME (ovi4)
My third successful attempt @ a basic "weather station" code inspired from other people's ideas
Hardware used:  - SSD1306-128x64-SPI-7pins-OLED
                           -  Arduino Uno board
                            - DHT22 aka (AM2302) temp./Humidity sensor.
All on breadboard and "Dupont" wires.    
*/
#include "U8glib.h"  // the needed OLED library where most of the magic happens !!!
#include "DHT.h"  // I've used : (https://github.com/markruys/arduino-DHT/archive/master.zip)

DHT dht; // to do with setting up an object ???

/*
Please note that (@ least in my case) the SSD1306 128x64 (SPI 7 pins) OLED display works by connecting the OLED's  RES pin to the RESET pin of the Arduino Uno board  and also works (funny enough) when selecting the SH1106 display from U8g the library list  and  then assigning pin 8 (Arduino) as the RES pin for the OLED onto the "equation" (which seems to have been forgotten )  see the code line below:
*/
U8GLIB_SH1106_128X64 u8g (13, 11 ,10 ,9 ,8 );     //D0=13,D1=11,CS=10,DC=9,Reset=8
// U8GLIB_SSD1306_128X64 u8g (13, 11, 10, 9 );  //SCK(DO)=13, MOSI(DI)=11 ,CS=10, //A0(DC)=9, RES=goes to RESET (on Arduino)

const uint8_t sunny_clouds []  PROGMEM = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00,
0x00, 0x00, 0x00, 0x30, 0x02, 0x00, 0x00, 0x00, 0x00, 0x20, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00,
0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x0F, 0x00, 0x00, 0x00, 0x00, 0x40, 0x7F, 0xC0, 0x00,
0x00, 0x00, 0x00, 0xC0, 0x20, 0x00, 0x00, 0x00, 0x01, 0x00, 0x10, 0x00, 0x00, 0x00, 0x03, 0x00,
0x08, 0x06, 0x00, 0x00, 0x0F, 0x00, 0x04, 0x0C, 0x00, 0x00, 0x7F, 0xC0, 0x06, 0x08, 0x00, 0x01,
0xC0, 0x70, 0x02, 0x00, 0x00, 0x02, 0x00, 0x18, 0x02, 0x00, 0x00, 0x04, 0x00, 0x04, 0x03, 0x00,
0x00, 0x08, 0x00, 0x02, 0x03, 0x00, 0x00, 0x10, 0x00, 0x01, 0x03, 0x00, 0x00, 0x20, 0x00, 0x01,
0x03, 0x00, 0x00, 0x60, 0x00, 0x00, 0x83, 0x00, 0x01, 0xC0, 0x00, 0x00, 0x82, 0x00, 0x06, 0x00,
0x00, 0x00, 0xC2, 0x00, 0x08, 0x00, 0x00, 0x00, 0xC4, 0x00, 0x10, 0x00, 0x00, 0x00, 0xFC, 0x0C,
0x10, 0x00, 0x00, 0x03, 0xFC, 0x1E, 0x20, 0x00, 0x00, 0x00, 0x06, 0x00, 0x20, 0x00, 0x00, 0x00,
0x03, 0x00, 0x20, 0x00, 0x00, 0x00, 0x01, 0x00, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x80, 0xE0, 0x00,
0x00, 0x00, 0x00, 0x80, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x80, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x80,
0x20, 0x00, 0x00, 0x00, 0x00, 0x80, 0x20, 0x00, 0x00, 0x00, 0x00, 0x80, 0x10, 0x00, 0x00, 0x00,
0x00, 0x80, 0x10, 0x00, 0x00, 0x00, 0x01, 0x00, 0x08, 0x00, 0x00, 0x00, 0x01, 0x00, 0x04, 0x00,
0x00, 0x00, 0x02, 0x00, 0x03, 0xC0, 0x00, 0x00, 0x1C, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xF0, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x00, 0x03,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x02,
};

void draw(void) {
  float temp = round(dht.getTemperature()*10)/10; //some math applyed to reading value
  u8g.drawBitmapP( 1, 11, 6, 50, sunny_clouds);  // puts bitmap on display
  u8g.setFont(u8g_font_unifont);  //font set
  u8g.drawStr(30, 15, "TEMPERATURE:");  //writes to display
  u8g.drawStr(53, 45, "HUMIDITY:");  //writes to display
  u8g.setPrintPos(70, 30);  //where print begins
  u8g.print(String(int(dht.getTemperature()))); //print int to string conversion
  u8g.setPrintPos(70, 60);  //where print begins
  u8g.print(String(int(dht.getHumidity())) + " %"); //print conversion + symbol
  u8g.drawStr(97, 30, "C");  //puts celsius letter C on display
  u8g.drawCircle(93, 21, 2); //puts celsius symbol circle next to C on display
}

void setup() {
  dht.setup(2); //DHT sensor set data pin to digital pin 2
}

void loop(void) {
  u8g.firstPage();  
  do {
    draw();
  } while( u8g.nextPage() );
//delay(dht.getMinimumSamplingPeriod()); //the minimal wait before DHT22 updates
 delay(3000);  // some delay before reading DHT22
}`
```
Conclusion:  For a beginner (like myself) the world of arduino coding is NOT what it seems to be. Any little detail (however insignificant it might be) could hold the key to a successful code. However despite all of the above "swing and roundabouts" and the sometimes overwhelmingly "steep" learning curve
I'm really starting liking it a lot. The sense of achievement is somewhat "HUGE"; the satisfaction of finding a solution to a "puzzling problem" and yet, so much more to be learned every day. 

I really need to get the grasp of C and/or C++ language since (is the official language used in micro-controllers such as Arduino etc) but @ the moment  my only language I ever studied "for a brief while" was python really! However, since C is more of a lower level language I find it a little harder to comprehend and that the strictness of it is unlike python's forgiveness should I say. :)))
On the other hand when it comes to putting the hardware together, there no problem at all since I have a background in electrics and electronics. 

Thank you once again for helping me out. 
All the best.
